version: "3.9"

volumes:
  openldap-vol:
    driver: local

services:
  openldap:
    container_name: openldap
    image: bitnami/openldap
    ports:
      - 1389:1389
      - 1636:1636
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_USERS=user01
      - LDAP_PASSWORDS=user01
    volumes:
      - "openldap-vol:/bitnami/openldap"