version: "3.9"

volumes:
  rabbitmq-vol:
    driver: local

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq-vol:/var/lib/rabbitmq