version: "3.9"

volumes:
  mongodb-vol:
    driver: local

services:
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - mongodb-vol:/data/configdb
      - mongodb-vol:/data/db